version: '3'
services:
  agent:
    image: datadog/agent:latest
    container_name: agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/datadog-agent/run:/opt/datadog-agent/run:rw
      - /proc/mounts:/host/proc/mounts:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
    environment:
      - DD_API_KEY=1ed1eba742b84b49409e3a8e2885a779
      - DD_LOGS_ENABLED=true
      - DD_PROCESS_AGENT_ENABLED=true
      - DD_HOSTNAME=node-web-app
      - DD_LOG_LEVEL=debug
      - DD_APM_ENABLED=true
      - SD_BACKEND=docker
      - NON_LOCAL_TRAFFIC=false
      - MAX_TRACES_PER_SECOND=1

  mongo:
    image: test-db/node_app:version1
    ports:
      - "27017:27017"
    hostname: mongo
    container_name: demo-mongo
    environment:
      - MONGO_INITDB_DATABASE=demo-mongo

  redis:
    image: redis:4.0.10
    ports:
      - "6379:6379"
    hostname: redis
    container_name: demo-redis

  demo:
    build:
        context: .
    ports:
      - "3000:3000"
    container_name: demo-app
    links:
      - agent
      - mongo
      - redis
